import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Send, CheckCircle2, Zap, Sun, Globe } from 'lucide-react';
import './TrackInfo.css';

const trackContent = {
  'future-fuels': {
    emoji: '🌍',
    icon: <Globe size={40} />,
    title: 'Future Fuels: Current Crisis',
    subtitle: 'Address real-world challenges around energy, environment, and climate.',
    description: `The current global energy crisis is not just a problem for the future; it is a challenge we face today. From fluctuating fuel prices to the accelerating impact of climate change, the need for sustainable and resilient energy systems has never been more urgent. This track invites innovators to rethink how we manage resources and prepare for environmental challenges.`,
    focusAreas: [
      {
        title: 'Sustainable Systems',
        desc: 'Develop frameworks for long-term energy sustainability and circular economies.'
      },
      {
        title: 'Resource Management',
        desc: 'Innovate ways to optimize water, food, and material usage in a resource-constrained world.'
      },
      {
        title: 'Disaster Preparedness',
        desc: 'Build tech that helps communities withstand and recover from environmental disasters.'
      },
      {
        title: 'Pollution Control',
        desc: 'Create active solutions for reducing carbon footprints and waste at the source.'
      }
    ],
    projects: [
      'Smart grid optimization for rural areas',
      'AI-driven disaster response platforms',
      'Sustainable urban waste-to-energy systems',
      'Real-time pollution tracking for industries'
    ],
    color: '#0891b2',
    bg: '#ecfeff'
  },
  'solar-as-source': {
    emoji: '☀️',
    icon: <Sun size={40} />,
    title: 'Solar as Source',
    subtitle: 'Harness the power of the sun to solve critical societal problems.',
    description: `Solar energy is the most abundant resource available to us, yet its potential remains largely untapped in critical sectors like healthcare tower and rural development. This track encourages participants to design products and services that use solar as a primary power source to enable cleaner mobility and smarter infrastructure.`,
    focusAreas: [
      {
        title: 'Solar IoT',
        desc: 'Connect remote sensors and devices using dedicated solar power modules.'
      },
      {
        title: 'Off-grid Solutions',
        desc: 'Provide reliable energy to regions without access to a traditional power grid.'
      },
      {
        title: 'Clean Mobility',
        desc: 'Design solar-integrated transportation solutions for a zero-emission future.'
      },
      {
        title: 'Smart Agriculture',
        desc: 'Use solar-powered automated systems for irrigation and crop monitoring.'
      }
    ],
    projects: [
      'Solar-powered portable cold storage for medicine',
      'Automated solar irrigation systems',
      'Solar-integrated electric vehicle charging stations',
      'Off-grid IoT weather stations'
    ],
    color: '#d97706',
    bg: '#fffbeb'
  },
  'alternative-energies': {
    emoji: '⚡',
    icon: <Zap size={40} />,
    title: 'Alternative Energies',
    subtitle: 'Explore non-traditional sources like wind, kinetic, and bio-energy.',
    description: `Beyond solar and traditional fuels lies a world of untapped power. From the wind that blows across our plains to the kinetic energy generated by our movement, alternative energy sources represent the next frontier of human innovation. This track focuses on reducing our dependence on fossil fuels through diverse technological paths.`,
    focusAreas: [
      {
        title: 'Wind Tech',
        desc: 'Innovate in small-scale wind turbine design and efficient power storage.'
      },
      {
        title: 'Bio-energy',
        desc: 'Convert organic waste and biological processes into sustainable fuel sources.'
      },
      {
        title: 'Kinetic Energy',
        desc: 'Capture everyday energy from movement, vibrations, or pressure.'
      },
      {
        title: 'Geothermal Solutions',
        desc: 'Utilize the Earth\'s natural heat for heating, cooling, or power generation.'
      }
    ],
    projects: [
      'Vertical axis wind turbines for urban houses',
      'Community-based biogas generation systems',
      'Kinetic energy harvesting floor tiles',
      'Small-scale geothermal heat pump systems'
    ],
    color: '#16a34a',
    bg: '#f0fdf4'
  }
};

export default function TrackInfo() {
  const { slug } = useParams();
  const track = trackContent[slug];

  if (!track) {
    return (
      <div className="track-info-error">
        <h2>Track Not Found</h2>
        <Link to="/" className="btn btn-primary">Back to Home</Link>
      </div>
    );
  }

  return (
    <div className="track-info-page" style={{ '--track-color': track.color, '--track-bg': track.bg }}>
      <div className="track-info-hero">
        <div className="container">
          <Link to="/" className="track-back-link">
            <ArrowLeft size={18} /> Back to Home
          </Link>
          <div className="track-hero-content">
            <div className="track-hero-icon">{track.icon}</div>
            <h1 className="track-hero-title">{track.title}</h1>
            <p className="track-hero-subtitle">{track.subtitle}</p>
          </div>
        </div>
      </div>

      <div className="track-info-body">
        <div className="container">
          <div className="track-grid">
            <div className="track-details">
              <section className="track-section">
                <h3>Overview</h3>
                <p className="track-long-desc">{track.description}</p>
              </section>

              <section className="track-section">
                <h3>Key Focus Areas</h3>
                <div className="focus-grid">
                  {track.focusAreas.map((area, i) => (
                    <div key={i} className="focus-card">
                      <CheckCircle2 className="focus-icon" size={20} />
                      <div>
                        <h4>{area.title}</h4>
                        <p>{area.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </section>

              <section className="track-section">
                <h3>Potential Project Ideas</h3>
                <ul className="project-list">
                  {track.projects.map((proj, i) => (
                    <li key={i}>{proj}</li>
                  ))}
                </ul>
              </section>
            </div>

            <div className="track-sidebar">
              <div className="sidebar-card">
                <h3>Judging Criteria</h3>
                <div className="criteria-list">
                  <div className="criteria-item">
                    <span className="criteria-label">Innovation</span>
                    <span className="criteria-val">30%</span>
                  </div>
                  <div className="criteria-item">
                    <span className="criteria-label">Technical Feasibility</span>
                    <span className="criteria-val">25%</span>
                  </div>
                  <div className="criteria-item">
                    <span className="criteria-label">Societal Impact</span>
                    <span className="criteria-val">25%</span>
                  </div>
                  <div className="criteria-item">
                    <span className="criteria-label">Presentation</span>
                    <span className="criteria-val">20%</span>
                  </div>
                </div>
              </div>

              <div className="sidebar-cta">
                <h3>Ready to build?</h3>
                <p>Registration is open until April 20th.</p>
                <Link to="/#register" className="btn btn-primary btn-block">
                  <Send size={16} /> Register for this Track
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
